### ISSUE TITLE
Configurable Logging Formats

### ISSUE THREAD

**Issue by skorfmann** [CodeCommission/subkit#14]
Logging was implemented via #9, which outputs raw json at the moment. Would be pretty nice to have configurable logging formats at some point. Besides the existing JSON logging, I have a nicely formatted text logging in mind.

**Comment by MikeBild** [comment]
`subkit serve --log-format text|json --log-style shot|extended`

**Comment by MikeBild** [comment]
release [v3.8.5](https://github.com/CodeCommission/subkit/releases/tag/v3.8.5)
