### ISSUE TITLE
Don't Mix Request and Persisted Queries

### ISSUE THREAD

**Issue by skorfmann** [CodeCommission/subkit#8]
# Intended outcome:

When I submit a query via GraphiQL with the same operation name as a persisted query, it runs the persisted query. This is confusing, since those queries might be different, in particular when it come s to input variables.

# Actual outcome:

The persisted query is executed

**Comment by MikeBild** [comment]
Is it easier to understand by preferring the execution of given query, instead of persistent query?

**Comment by skorfmann** [comment]
I think so, yes - it's sort of a temporary overwrite of the persisted query.

**Comment by MikeBild** [comment]
[v3.8.4](https://github.com/CodeCommission/subkit/releases/tag/v3.8.4)

**Comment by MikeBild** [comment]
Can that be closed?
