### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by skorfmann** [CodeCommission/subkit#9]
It would be helpful to have an option to log requests. Things I'd expect to see in a log:

- Full request
- Full Query which is executed
- Type of query: Request / Persisted
- Variables used for that query
- Operation Name

**Comment by MikeBild** [comment]
-> [v3.2.7](https://github.com/CodeCommission/subkit/releases/tag/v3.8.1) release

**Comment by skorfmann** [comment]
Cool, thanks! 👍
